project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "files/"
    - "projects/"

website:
  title: "A glitch in the matrix"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



