---
title: 'Presentazione per AC: lessico addomesticato e pensiero addormentato'
categories: ['spunti', 'lexicon', 'ENG 🇺🇸', 'ITA 🇮🇹']
date: 2025-02-13
toc: TRUE
draft: TRUE
image: ""
image-alt: ""
lang: it
---

https://www.philosopheasy.com/p/mind-control-101-language-and-reality?r=7roap&triedRedirect=true

> Language plays a central role in this form of warfare, as it is used to spread propaganda, create division, and exploit vulnerabilities in people's cognitive biases.


# Buone notizie

2. cuore: abbiamo in dotazione uno strumento infallibile per distinguere il vero dal falso, il giusto dall'ingiusto, il bello dal brutto
	i. Giussani
	ii. Ratzinger
	iii. Moro e il linguaggio universale
	
	
# PPP	

We need:

+ media literacy
+ critical thinking skills
+ a deep understanding of how language works, how it can be used to manipulate, and how to resist such manipulation.

Or, the way I see it: 

1. **Giudicare le idee** facendosi domande // habit of critical thinking / curiosity
	i. Ma proprio proprio questa parola cosa vuol dire?
	ii. Ma questa idea da dove arriva (e come si è trasformata e/o deviata)?
		 - Esempi: "sviluppo sostenibile" in *Our common good*
	iii. Confrontarsi con le idee altrui e ascoltare le ragioni di chi la pensa diversamente

2. **Giudicare azioni** (politiche, proposte, programmi, leggi) risalendo alle idee che le ispirano
	i. Cercare di identificare i "first principles" che ispirano un'azione e verificare (va da se)
	ii. e io li condivido Questa proposta/intervento/programma chi avvantaggia?
	iii. "Qui prodest"?
	iv. follow the money 

5. Il primato della realta ( ~ ascoltare la voce di chi è piu vicino alla realta )

3. Connettere i puntini
	i. Esempi...
 
4. Diventare consapevoli della cornice valoriale usata nella comuncazione
	i. Esempi...
	
	> For example, describing a government program as "tax cuts for the wealthy" versus "incentives for job creators" evokes vastly different responses, even though the underlying policy is the same.

# Gli altri


+ [Super Europa necessaria per Draghi e Mattarella](https://www.linkiesta.it/2025/02/mattarella-draghi-meloni-trump/)
+ [Draghi Super UE](https://www.linkiesta.it/2025/02/mario-draghi-discorso-parlamento-europeo-febbraio/)

>	"**ragioni dietro gli alti prezzi dell’energia in Europa**: 
>
>	+ al di là del fatto che l’Ue non sia un grande produttore di gas naturale. 
>	+ la limitata coordinazione degli acquisti nazionali di gas, 
>	+ il funzionamento del mercato energetico, 
>	+ i ritardi nell’installazione della capacità rinnovabile, 
>	+ le reti poco sviluppate, 
>	+ l’elevata tassazione e gli alti margini finanziari. 
>		
> Tutti questi fattori sono il risultato delle nostre stesse decisioni, e quindi possono essere modificati se abbiamo la volontà di farlo."

> "il rapporto affronta diverse vulnerabilità dell’Europa, una delle quali è il nostro **sistema di difesa**. La frammentazione della capacità industriale lungo linee nazionali impedisce di raggiungere la scala necessaria. Anche se collettivamente siamo il terzo maggiore investitore in difesa al mondo, non saremmo in grado di soddisfare un aumento della spesa per la difesa attraverso la nostra stessa capacità produttiva. I nostri sistemi di difesa nazionali non sono né interoperabili né standardizzati in alcune parti chiave della catena di approvvigionamento. Questo è uno dei tanti esempi in cui l’Unione Europea è meno della somma delle sue parti."
